const strings = {
  PRINT_SHEETS: "Yenting Chen", // "拼學趣",
  CAPTCHA_CODE: "Captcha Code", //驗證碼 (不分大小寫)",  
  CREATE_AN_ACCOUNT_FAST: "Register", //快速註冊",
  NICK_NAME: "Nick name", //"暱稱",
  EMAIL: "Email", //"電子信箱",
  PASSWORD: "Password", //"密碼",
  PASSWORD_CONFIRM: "Password Confirm", //"密碼確認",
  EMAIL_CONFIRM: "Email Confirm", //"信箱確認",
  SIGN_UP: "Register", //註冊",
  LOGIN: "Login", //"登入",
  LOGOUT: "Logout", //"登出",
  ALREADY_HAVE_ACCOUNT_Q: "Already registered?",//"已經有帳號了?",
  CREATE_AN_ACCOUNT: "Create an account", // "建立一個帳號",
  REFRESH: "Refresh", //重新整理",
  FORGET_PWD_Q: "Forget password?", //"忘記密碼?",
  FORGET_PWD: "Forget password", // "忘記密碼",
  RESET_PWD: "Reset password", // "重設密碼",
  CONFIRM_AND_SEND: "Send", //"確認送出",
  EDIT_DATA_PWD: "Member Data Edit",//"修改資料/密碼",
  PLZ_INPUT_OLD_PWD: "Please input current password", // "請輸入舊密碼",
  PLZ_INPUT_NEW_PWD: "Please input new password", // "請輸入新密碼",
  PLZ_INPUT_NEW_PWD_AGAIN: "Please input new password again", // "請再次輸入新密碼",
  BACK_2_HOME: "回首頁",
  HOME_PAGE: "Home Page", // "首頁",
  CATEGORY: "分類",
  EDIT_SUCCESS: "您的資料已更改完成",
  WORK_NAME: "Title", // "作品名稱",
  EDIT: "Edit", // "編輯",
  DELETE: "Delete", // "刪除",
  CREATION_DATE: "Creation Date", // "建立日期",
  UPLOAD_FAILED: "Upload Failed", // "上傳失敗",
  UPLOAD: "Upload", // "上傳", 
  UPLOADING_PLZ_WIAT: "Uploading, please wait", // "上傳中，請稍候",
  SAVING: "Saving", // "儲存中",
  STATUS: "Visibility", //"狀態",
  VISIBLE: "Visible",// "顯示",
  HIDDEN: "Hidden", // "隱藏",
  ALL: "All",// "全部",
  SHOW_IN_FRONT_PAGE: "Show in home page", // "首頁顯示",
  MAIN_CATEGORY: "主要分類",
  WORK_SERIAL_AND_MODEL: "作品型號/編號",
  VISIBLE_PERIOD: "顯示期間",
  END_TIME_IS_OPTIONAL_WITHOUT_IT_WILL_SHOW_FOREVER: "可以不設定結束時間, 將為常態顯示",
  WORK_PICTURE: "Image", // "作品圖",
  FILE_SIZE_UNDER_1MB_RECOMMANDED: "",// "檔案大小建議在1MB以下",
  DATA_SOURCE: "資料來源",
  WORK_DETAIL_DESCRIPTION: "Abstract", // "作品詳細說明",
  DOWNLOAD_INSTRUCTION: "Detail Description", // "下載方式",
  YES: "Yes",// "是",
  NO: "No", // "否",
  OPTIONAL: "Optional", // "可不填",
  PLZ_PASTE_YOUTUBE_VIDEO_URL_OR_VIDEO_EMBEDDED_INFO: "Please input youtue video url", // "請貼上youtube影片網址，或臉書等其他網站影片嵌入資訊",
  KEYWORD: "Title Keyword",// "關鍵字"
 };

export default strings;