module.exports = {
  emailError: 'Please input validate email address.',// '請輸入有效的電子信箱',
  passwordNotLongEnough: 'At least four characters long for password',// '密碼至少要四個字元',
  nameEmtyp: 'Please input nick name',// '請輸入暱稱',
  pwdEmpty: 'Please input password',// '請輸入密碼',
  PLZ_INPUT_WORK_TITLE: 'Please input tile',// "請輸入作品名稱",
  PLZ_UPLOAD_WORK_IMG: 'Please upload image', // "請上傳作品圖",
  PLZ_INPUT_WORK_DESC: 'Please input abstract', // "請輸入作品詳細說明",
  PLZ_INPUT_DOWNLOAD_INSTRUCTIONS: 'Please input detail description',// "請輸入下載方式",
  PLZ_INPUT_CATEGORY_NAME: "請輸入類別名稱",
  captcahInputError: 'Captcha input error', // '驗證碼輸入錯誤',
  formDataError: 'Form data error',// '表單內容錯誤',
  emailTaken: 'Email Registered',// '此電子信箱已註冊',
  signupFailed: '註冊失敗',
  INCORRECT_EMAIL_OR_PWD: 'Account or password error',// '帳號或密碼錯誤',
  LOGIN_FAILED: '登入失敗',
  SAVE_DATA_FAILED: '資料儲存失敗',
  signupCompleteGoLoginPlz: 'Register success, please login.',// '註冊完成! 請登入',
  loginComplte: '登入成功!',
  PASSWORD_NOT_EQUAL: 'Password not equal',// '密碼不相符',
  PASSWORD_INCORRECT: 'Password incorrect',// '密碼不正確',
  EMAIL_NOT_EQUAL: 'Email not equal',// '信箱不相符',
  ACCOUNT_NOT_EXIST: 'Account not exist', // '帳號不存在',
  LINK_EXPIRED: '連結已過期'
};